### PR TITLE
Add task for initial setup for MySQL slave

### PR DESCRIPTION
**Pull request by alexmuller**

### CODE REVIEW

**Comment by surminus** [comment]
Might be useful to mention somewhere that running this might take a while (often without output) for the impatient folks in this world.

**Comment by alexmuller** [comment]
Good point, pushed a couple of commits to help with that.

**Comment by surminus** [comment]
Worked really well when I ran this. Hooray for automating stuff. :+1:

**Comment by mattbostock** [comment]
:+1:

**Pull request merged**
