### PR TITLE
Task to respawn large unicorn workers

### PR DESCRIPTION
**Pull request by boffbowsh**
In lieu of an automated Icinga event handler to solve issues with high
memory for certain apps, this script will gracefully kill the largest
unicorn worker for a specified app.

It issues a `SIGQUIT` to the worker which will tell it to finish serving
the current request then exit. The master will notice this and fork a
new worker with less bloat.

Usage:
```
$ fab integration class:backend numbered:1 app.respawn_large_unicorns:tariff_api
[backend-1.backend] Executing task 'numbered'
[backend-1.backend] Executing task 'app.respawn_large_unicorns'
[backend-1.backend] run: cat /var/run/tariff-api/app.pid
[backend-1.backend] out: 4811
[backend-1.backend] out:

[backend-1.backend] run: cat /proc/4811/cmdline
[backend-1.backend] out: unicorn master -D -P /var/run/tariff-api/app.pid -p 3018 -c /var/apps/tariff-api/config/unicorn.rb
[backend-1.backend] sudo: kill -QUIT $(ps -o rss,pid --ppid 4811 --sort +rss | tail -n1 | awk '{print $2}')
```

/cc @surminus

### CODE REVIEW

**Comment by mattbostock** [comment]
@boffbowsh What are the advantages of this over reloading an application? We should document this command so that it's clear when it should be used.

**Comment by boffbowsh** [comment]
This was simply a convenience task in lieu of having the main Icinga event handler stuff merged. However, I do still think this is the best approach, which should be extended to automatically kill bloated workers individually before they start to run the box out of RAM and thus trigger an Icinga alert.

At the moment, this is just a simple way of solving a "high memory for x app on y server" Icinga alert.

**Comment by mattbostock** [comment]
@boffbowsh Not disputing the approach but I don't know if the benefits are obvious to others. Could we add something to the Ops Manual under the 'high memory alert' section?

**Comment by boffbowsh** [comment]
Good point. See https://github.gds/gds/opsmanual/pull/627

**Pull request merged**
