### PR TITLE
[DO NOT MERGE] Update fabric to work with AWS

### PR DESCRIPTION
**Pull request by surminus**
### This branch should only be merged when we have entirely migrated to AWS.

This allows working in AWS, and optionally specifying a stack name.
Normal usage:

`fab integration all hosts`

Specify a stack:

`fab integration:green all hosts`

This assumes that a jumpbox for that stack exists.

### CODE REVIEW

**Comment by surminus** [comment]
Unfortunately this doesn't work.

**Comment by surminus** [comment]
While this works, it does something odd with the fabric commands. For example:

```
🐦  ~/govuk/fabric-scripts git:(fabric-for-aws) fab aws:"integration,blue" class:backend puppet

Warning: Your fabric-scripts may be out-of-date. Please `git pull` the repo


Warning: Command(s) not found:
    puppet
```

**Comment by surminus** [comment]
You're right, it does seem to work with the current environments. If you're happy to merge, I'll do it. We can always revert.

**Comment by danielroseman** [comment]
This seems to have broken running fab scripts against staging at least.

**Comment by boffbowsh** [comment]
Yep, I'm looking into these at the moment

**Comment by boffbowsh** [comment]
@danielroseman does the `fix-for-carrenza` branch work for you?

**Comment by danielroseman** [comment]
@boffbowsh yes, seems to.

**Pull request merged**
