### PR TITLE
Remove licensify task

### PR DESCRIPTION
**Pull request by mattbostock**
Remove the licensify task; we have centralised logging using Kibana so
this task for grepping logs is not necessary.

### CODE REVIEW

**Comment by alexmuller** [comment]
Tests have failed, but it seems like they should have failed on #204 instead of this pull request.

**Comment by mattbostock** [comment]
I've pushed ab03648 to fix. I'll look into why it didn't fail earlier.

**Comment by mattbostock** [comment]
So, it looks like the tests didn't fail in #204 because they were [still](https://github.com/alphagov/fabric-scripts/blob/4b34e16a33e95ff967f1eeb091579948a8b42563/Makefile) using the broken Makefile which split the parameters to `flake8` over two lines, which was fixed in 5090aef59.

It seems that if you have a trailing comma in the `--ignore` option, `flake8` ignores _all_ transgressions, which explains why the tests didn't fail in #204. That's based on my brief testing.

This is ready for review now.

**Comment by mattbostock** [comment]
_bump_

**Comment by surminus** [comment]
:+1: LGTM

**Pull request merged**
